### ISSUE TITLE
Receiver setup

### ISSUE THREAD

**Issue by mloubout** [opesci/inversion_codegen#1]
@navjotk @ggorman 

I see that now, the receiver location (xrec) is defined as an attribute of the propagator. It should be defined the same ways as the source, mainly
 xrec= self.data.get_rec_loc()
or something like that. All data related parameter (source location, receiver location,...) have to be inside the data object not the propagator.

**Comment by navjotk** [comment]
Alright. I'll make this change here. Thanks for pointing it out.
